from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'groups.views.home', name='home'),
    url(r'^register$', 'groups.views.register', name='register'),
    url(r'^login$', 'groups.views.login', name='login'),
    url(r'^logout$', 'groups.views.logout', name='logout'),
    url(r'^guide$', 'groups.views.guide', name='guide'),
    url(r'^explore$', 'groups.views.home', name='home'),
    url(r'^explore_topic$', 'groups.views.explore_topic', name='explore_topic'),
    url(r'^mygroup/$', 'groups.views.mygroup', name='mygroup'),
    url(r'^my_topics/$', 'groups.views.my_topics', name='my_topics'),
    url(r'^my_replied_topics/$', 'groups.views.my_replied_topics', name='my_replied_topics'),
    url(r'^mine/$', 'groups.views.mine', name='mine'),
    url(r'^join$', 'groups.views.groupjoin', name='groupjoin'),
    url(r'^new_group$', 'groups.views.new_group', name='new_group'),
    url(r'^(?P<gname>(.*?))/new_topic$', 'groups.views.new_topic', name='new_topic'),
    url(r'^get_captcha$', 'groups.views.get_captcha', name='get_captcha'),
    url(r'^search$', 'groups.views.search', name='search'),
    url(r'^topic/(?P<id>\d+)$', 'groups.views.topic', name='topic'),
    url(r'^topic/(?P<id>\d+)/remove_comment$', 'groups.views.remove_comment', name='remove_comment'),
    url(r'^topic/(?P<id>\d+)/admin_remove$', 'groups.views.admin_remove', name='admin_remove'),
    url(r'^show/(?P<gname>(.*?))/$', 'groups.views.showgroup', name='showgroup'),
    url(r'^topic/add_comment/(\d+)$', 'groups.views.add_comment', name='add_comment'),
    url(r'^(?P<gname>(.*?))/group_edit/$', 'groups.views.group_edit', name='group_edit'),
    url(r'^(?P<gname>(.*?))/members/$', 'groups.views.members', name='members'),
    url(r'^(?P<gname>(.*?))/advance/$', 'groups.views.advance', name='advance'),
    url(r'^add_friendgroup/$', 'groups.views.add_friendgroup', name='add_friendgroup'),
    url(r'^change_privacy/$', 'groups.views.change_privacy', name='change_privacy'),
    url(r'^change_join/$', 'groups.views.change_join', name='change_join'),
    url(r'^user_report/$', 'groups.views.user_report', name='user_report'),
    url(r'^upload-images/$', 'groups.views.upload_images', name='upload_images'),
    url(r'^del_image/$', 'groups.views.del_image', name='del_image'),
	url(r'^(.*?).htm$','groups.views.dispatcher',name='dispatcher'),
)
